### ISSUE TITLE
About the sections removed from the 3rd edition

### ISSUE THREAD

**Issue by kanition** [mmp/pbr-book-website#14]
Hi~ I'm very excited about the release of the 4th edtion! Many thanks to all of the authors and contributors. I'm sure it's an excellent book. 

I note that some sections from the 3rd edtion are removed after updating. For example, in Chapter 1~8:
- Animating Transformations
- Subdivision Surfaces
- Kd-Tree Accelerator
- Realistic Cameras
- (0, 2)-Sequence Sampler
- Maximized Minimal Distance Sampler

Are there any special reasons for removing them?

**Comment by lobneroO** [comment]
I just noticed the same, especially the old chapter 16 Light Transport III: Bidirectional Methods is missing in the 4th edition despite stochastic progressive photon mapping (as an example) being mentioned in the introduction in chapter 1.2.

**Comment by mmp** [comment]
They're not there because they're not in the printed book. (They were cut for page count there and were things that we didn't have much new to say about versus in the third edition.)

The (0,2)-sequence sampler section is subsumed by the Sobol' sampler section. (Same thing, different name.)

We have plans to update the online edition to include most of that, but the text isn't ready yet. It will probably be a few months.
